<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="Content-type" content="text/html; charset=iso-8859-2">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>EXTRANET 2.0</title>

        <link href="<?= $this->basePath() . '/css/bootstrap.min.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/css/plugins/metisMenu/metisMenu.min.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/css/sb-admin-2.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/font-awesome/css/font-awesome.min.css' ?>" rel="stylesheet" type="text/css">
        <link href="<?= $this->basePath() . '/css/fullcalendar.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/css/datepicker.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/css/fullcalendar.print.css' ?>" rel="stylesheet" media="print">
        <link href="<?= $this->basePath() . '/css/custom.css' ?>" rel="stylesheet">
        <link href="<?= $this->basePath() . '/css/jquery.timepicker.css' ?>" rel="stylesheet">
        <script src="<?= $this->basePath() . '/js/jquery.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/bootstrap.min.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/plugins/metisMenu/metisMenu.min.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/sb-admin-2.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/moment.min.js' ?>"></script> 
        <script src="<?= $this->basePath() . '/js/jquery-1.9.1.min.js' ?>"></script>
        <script  src="<?= $this->basePath() . '/js/jquery-ui-1.10.2.custom.min.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/jquery-ui.custom.min.js' ?>"></script>
        <script  src="<?= $this->basePath() . '/js/jquery.timepicker.js' ?>"></script>
        <script  src="<?= $this->basePath() . '/js/jquery.datepair.js' ?>"></script>
        <script  src="<?= $this->basePath() . '/js/datepair.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/jquery.min.js' ?>"></script>
        <script  src="<?= $this->basePath() . '/js/bootstrap-datepicker.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/fullcalendar.min.js' ?>"></script>
        <script src="<?= $this->basePath() . '/js/pl.js' ?>"></script>       
    </head>
    <body>
        <div id="wrapper">
            <nav class="navbar navbar-default navbar-static-top" role="navigation" id="up-nav" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-brand">EXTRANET 2.0</a>
                </div>
                <ul class="nav navbar-top-links navbar-left">
                        <li>
                            <a href='<?= $this->url('zarzadzanie', array()); ?>'><i class="fa fa-futbol-o"></i>  Zarządzanie meczami</a>
                        </li>   
                        <li>
                            <a href='<?= $this->url('sprawozdanie', array()); ?>'><i class="fa fa-pencil"></i>  Tworzenie sprawozdań</a>
                        </li>
                    <li>
                        <a href='<?= $this->url('podglad', array()); ?>'><i class="fa fa-search"></i>  Podgląd sprawozdań</a>
                    </li>                
                </ul>
                <ul class="nav navbar-top-links navbar-right">
                    <li class="dropdown">

                        <a class="dropdown-toggle" data-toggle="dropdown" href="">
                            <i class="fa fa-user fa-fw"></i> <?= $_SESSION['name']; ?> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                           
                            <li><a href="<?= $this->url('logout'); ?>"><i class="fa fa-sign-out fa-fw"></i> Wyloguj</a>
                            </li>
                        </ul>

                    </li>
                </ul>
            </nav>
            <div id="page-wrapper" style="margin: auto">
                <div class="container-fluid">

                    <div class="col-lg-12">
                        <h1 class="page-header">
                        </h1>
                    </div>

                    <?php echo $this->content; ?>
                </div>
                <hr/>
            </div>
        </div>


    </body>
</html>
