<h1 class="page-header">Zmiana hasła:</h1>
<div class="col-lg-6">
<form enctype="multipart/form-data" action="<?= $this->url(array('action' => 'zmianahasla')); ?>" method="post">
    <div class="form-group">
        <label>Podaj nowe hasło:</label>
                <input type="password" name="Haslo" class="form-control" placeholder="Hasło"/>
    </div>
    <div class="form-group">
        <label>Powtórz hasło:</label>
                <input type="password" name="Haslo1" class="form-control" placeholder="Powtórzone hasło"/>
    </div>
     
                <a href="<?= $this->url('podglad',array()); ?>"><input class="btn btn-default" type="button" value="Wstecz" />
                <a href="<?= $this->url('zmianahasla'); ?>"><button type="submit" class="btn btn-default">Zatwierdź</button></a>
                <button type="reset" class="btn btn-default" onclick="return confirm('Dane zostaną zresetowane')">Wyczyść</button>
</a>

</form>
</div>