
<h1 class="page-header">Lista zawodników:</h1>
<div class="col-lg-12">
    <div class="table-responsive">
        <table class="table table-bordered table-striped table-hover">
            <thead>
            <tr>
            <th>Imię</th>
            <th>Nazwisko</th>
            <th>Data urodzenia</th>
            <th>Klub</th>
            <th>Zaznacz</th>
        </tr>
            </thead>
            <?php foreach ($zawodnicy as $zawodnik) : ?>
    <tr>
    <td><?= $this->escapeHtml($zawodnik->z_imie) ?></td>
    <td><?= $this->escapeHtml($zawodnik->z_nazwisko) ?></td>
    <td><?= $this->escapeHtml($zawodnik->z_data_ur) ?></td>
    <td><?= $this->escapeHtml($zawodnik->id_zespol) ?></td>
     <td><input type="radio" value="<?= $this->escapeHtml($zawodnik->id_zawodnik) ?>" name="choice" /></td>

    </tr>

<?php endforeach; ?>


    </table>
    

        </div>
</div>

<br/>
<br/>

<a href="<?= $this->url('zawodnik',array('action'=>'dodaj')) ?>"><button class="btn btn-default">Nowy</button></a>&nbsp;&nbsp;
<a id="adresEdytuj" href="<?= $this->url('zawodnik',array('action'=>'edytuj')); ?>"><button class="btn btn-default">Edytuj</button></a>&nbsp;&nbsp;


<a id="adresUsun" href="<?= $this->url('zawodnik',array('action'=>'usun')); ?>"><button class="btn btn-default" onclick="return confirm('Czy chcesz usunąć tego zawodnika?')">Usuń</button></a>&nbsp;&nbsp;

<br/>
<br/>
   
   
<script>
    
    tekstEdytuj=document.getElementById("adresEdytuj").getAttributeNode("href").value;
    tekstUsun=document.getElementById("adresUsun").getAttributeNode("href").value;
    
    function getCheckboxesValues() {
        return [].slice.apply(document.querySelectorAll("input[type=radio]"))
                .filter(function (c) {
                    return c.checked;
                })
                .map(function (c) {
                    return c.value;
                });
    }

    $(document.querySelectorAll("input[type=radio]")).change(function() {
    document.getElementById("adresEdytuj").getAttributeNode("href").value=tekstEdytuj+getCheckboxesValues();
    document.getElementById("adresUsun").getAttributeNode("href").value=tekstUsun+getCheckboxesValues();
});
    
</script>    